<a href="https://colab.research.google.com/github/Aishwaryakote/BagOfWords/blob/main/Bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bag-of-words**

Bag-of-words(BoW) is a statistical language model used to analyze text and documents based on word count. The model does not account for word order within a document. BoW can be implemented as a Python dictionary with each key set to a word and each value set to the number of times that word appears in a text.

In [1]:
documents = ['Hello, how are you!',
             'Win money, win from home.',
             'Call me now.',
             'Hello, Call hello you tomorrow?']

In [2]:
lower_case_documents = []
for i in documents:
   lower_case_documents.append(i.lower())   
print(lower_case_documents)

['hello, how are you!', 'win money, win from home.', 'call me now.', 'hello, call hello you tomorrow?']


In [3]:
sans_punctuation_documents = []
import string

for i in lower_case_documents:
    sans_punctuation_documents.append(''.join(c for c in i if c not in string.punctuation))
    
print(sans_punctuation_documents)

['hello how are you', 'win money win from home', 'call me now', 'hello call hello you tomorrow']


In [4]:
preprocessed_documents = []
for i in sans_punctuation_documents:
    preprocessed_documents.append(i.split(' '))
print(preprocessed_documents)

[['hello', 'how', 'are', 'you'], ['win', 'money', 'win', 'from', 'home'], ['call', 'me', 'now'], ['hello', 'call', 'hello', 'you', 'tomorrow']]


In [5]:
frequency_list = []
import pprint
from collections import Counter

for i in preprocessed_documents:
    frequency_list.append(Counter(i))
    
pprint.pprint(frequency_list)

[Counter({'hello': 1, 'how': 1, 'are': 1, 'you': 1}),
 Counter({'win': 2, 'money': 1, 'from': 1, 'home': 1}),
 Counter({'call': 1, 'me': 1, 'now': 1}),
 Counter({'hello': 2, 'call': 1, 'you': 1, 'tomorrow': 1})]


In [6]:
import pandas as pd
documents = ['Hello, how are you!',
                'Win money, win from home.',
                'Call me now.',
                'Hello, Call hello you tomorrow?']

In [13]:
documents =[ 'Sachin is a great indian cricket player',

            'virat is the captain of the indian cricket team']

In [8]:
 documents = [ 'Sachin is a great Indian Cricket Player.',
 'Virat is the Captain of the Indian Cricket team.']

In [14]:
lower_case_documents = []
for i in documents:
    lower_case_documents.append(i.lower())
print(lower_case_documents)

['sachin is a great indian cricket player', 'virat is the captain of the indian cricket team']


In [15]:
sans_punctuation_documents = []
import string

for i in lower_case_documents:
    sans_punctuation_documents.append(''.join(c for c in i if c not in string.punctuation))
    
print(sans_punctuation_documents)

['sachin is a great indian cricket player', 'virat is the captain of the indian cricket team']


In [16]:
preprocessed_documents = []
for i in sans_punctuation_documents:
    preprocessed_documents.append(i.split(' '))
print(preprocessed_documents)

[['sachin', 'is', 'a', 'great', 'indian', 'cricket', 'player'], ['virat', 'is', 'the', 'captain', 'of', 'the', 'indian', 'cricket', 'team']]


In [17]:
frequency_list = []
import pprint
from collections import Counter

for i in preprocessed_documents:
    frequency_list.append(Counter(i))
    
pprint.pprint(frequency_list)

[Counter({'sachin': 1,
          'is': 1,
          'a': 1,
          'great': 1,
          'indian': 1,
          'cricket': 1,
          'player': 1}),
 Counter({'the': 2,
          'virat': 1,
          'is': 1,
          'captain': 1,
          'of': 1,
          'indian': 1,
          'cricket': 1,
          'team': 1})]


In [18]:
import pandas as pd
documents = [ 'Sachin is a great indian cricket player',
 'virat is the captain of the indian cricket team']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer(documents)

In [ ]:
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8',
                input=['Sachin is a great indian cricket player',
                       'virat is the captain of the indian cricket team'],
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [ ]:
count_vector.fit(documents)
count_vector.get_feature_names()

['captain',
 'cricket',
 'great',
 'indian',
 'is',
 'of',
 'player',
 'sachin',
 'team',
 'the',
 'virat']

In [ ]:
doc_array = count_vector.transform(documents).toarray()
doc_array

array([[0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1]])

In [ ]:
frequency_matrix = pd.DataFrame(doc_array,index=documents,columns=count_vector.get_feature_names())
frequency_matrix

captain  cricket  ...  the  virat
Sachin is a great indian cricket player                0        1  ...    0      0
virat is the captain of the indian cricket team        1        1  ...    2      1

[2 rows x 11 columns]

In [ ]:
documents = ['Welcome to Great Learning, Now start learning!!.',

            'Learning is a good practice.']

In [ ]:
lower_case_documents = []
for i in documents:
    lower_case_documents.append(i.lower())
print(lower_case_documents)

['welcome to great learning, now start learning!!.', 'learning is a good practice.']


In [ ]:
sans_punctuation_documents = []
import string

for i in lower_case_documents:
    sans_punctuation_documents.append(''.join(c for c in i if c not in string.punctuation))
    
print(sans_punctuation_documents)

['welcome to great learning now start learning', 'learning is a good practice']


In [ ]:
preprocessed_documents = []
for i in sans_punctuation_documents:
    preprocessed_documents.append(i.split(' '))
print(preprocessed_documents)

[['welcome', 'to', 'great', 'learning', 'now', 'start', 'learning'], ['learning', 'is', 'a', 'good', 'practice']]


In [ ]:
frequency_list = []
import pprint
from collections import Counter

for i in preprocessed_documents:
    frequency_list.append(Counter(i))
    
pprint.pprint(frequency_list)

[Counter({'learning': 2,
          'welcome': 1,
          'to': 1,
          'great': 1,
          'now': 1,
          'start': 1}),
 Counter({'learning': 1, 'is': 1, 'a': 1, 'good': 1, 'practice': 1})]


In [ ]:
import pandas as pd
documents = ['Welcome to Great Learning, Now start learning.',

            'Learning is a good practice.']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer(documents)

In [ ]:
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8',
                input=['Welcome to Great Learning, Now start learning.',
                       'Learning is a good practice.'],
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [ ]:
count_vector.fit(documents)
count_vector.get_feature_names()

['good',
 'great',
 'is',
 'learning',
 'now',
 'practice',
 'start',
 'to',
 'welcome']

In [ ]:
doc_array = count_vector.transform(documents).toarray()
doc_array

array([[0, 1, 0, 2, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 0, 0]])

In [ ]:

frequency_matrix = pd.DataFrame(doc_array,index=documents,columns=count_vector.get_feature_names())
frequency_matrix

good  great  ...  to  welcome
Welcome to Great Learning, Now start learning.     0      1  ...   1        1
Learning is a good practice.                       1      0  ...   0        0

[2 rows x 9 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
string = ["This burger is tasty , The food is delicious, The food is awful"] 
vectorizer = CountVectorizer()
X=vectorizer.fit_transform(string)

In [ ]:
print (vectorizer.get_feature_names())
print (X.toarray())

['awful', 'burger', 'delicious', 'food', 'is', 'tasty', 'the', 'this']
[[1 1 1 2 3 1 2 1]]
